### PR TITLE
Completed the application

### PR DESCRIPTION
**Pull request by tavishjain**
Added Google Sign In

### CODE REVIEW

**Comment by tavishjain** [comment]
@deepanshib 

whatsapp image 2018-07-09 at 11 57 32 am
whatsapp image 2018-07-09 at 11 57 32 am 1

**Comment by tavishjain** [comment]
@deepanshib Completed the app and added screenshots below


whatsapp image 2018-07-09 at 5 36 48 pm 6
whatsapp image 2018-07-09 at 5 36 48 pm 5
whatsapp image 2018-07-09 at 5 36 48 pm 4
whatsapp image 2018-07-09 at 5 36 48 pm 3
whatsapp image 2018-07-09 at 5 36 48 pm 2
whatsapp image 2018-07-09 at 5 36 48 pm 1
whatsapp image 2018-07-09 at 5 36 48 pm

**Comment by deepanshib** [comment]
@tavishjain  you have not added google services json file in the folder.

**Comment by tavishjain** [comment]
@deepanshib  Yes I know that . It is a file for personal use right and is not a thing to be uploaded publicaly. I hope you know that

**Pull request merged**
